# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'paiming.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
import pymysql
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(850, 700)
        MainWindow.setMinimumSize(QtCore.QSize(850, 700))
        MainWindow.setMaximumSize(QtCore.QSize(850, 700))
        MainWindow.setStyleSheet("background-image: url(微信图片_20220501225953.png);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(100, 80, 91, 41))
        self.label.setStyleSheet("border-top:0px solid #e8f3f9;background:  transparent; ")
        self.label.setObjectName("label")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(80, 170, 311, 441))
        self.tableWidget.setStyleSheet("border-top:0px solid #e8f3f9;background:  transparent; ")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(270, 80, 111, 41))
        self.comboBox.setStyleSheet("border-radius: 10px;  border: 2px groove gray;\n"
"border-style: outset;")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(440, 80, 101, 41))
        self.pushButton.setStyleSheet("border-radius: 10px;  border: 2px groove gray;\n"
"border-style: outset;")
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 850, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.tableWidget.horizontalHeader().setStyleSheet("QHeaderView::section{background-color:rgb(255, 0,0, 0);"
                                                          "font:11pt '宋体';color: black;};")
        self.tableWidget.verticalHeader().setStyleSheet("QHeaderView::section{background-color:rgb(255, 0,0, 0);"
                                                        "font:11pt '宋体';color: black;};")
        self.comboBox.setStyleSheet("border-radius: 13px;  border: 2px groove gray;\n"
                                    "border-style: outset;\n"
                                    )


        self.pushButton.clicked.connect(self.chaxun)

    def chaxun(self):
        conn = pymysql.connect(
            host="localhost",
            user="root",
            password="987433",
            database="keshe01",
            charset="utf8"
        )
        cursor = conn.cursor()  # 得到一个可执行的游标对象
        xuanxiang = self.comboBox.currentText()
        try:
            if xuanxiang == '班级总分':
                sql1 = ("SELECT class.banjibianhao,sum(choose.score) FROM belong,class,choose "
                    "where belong.banjibianhao=class.banjibianhao GROUP BY class.banjibianhao")
                cursor.execute(sql1)
                data1 = cursor.fetchall()
                row_num = len(data1)
                self.tableWidget.setRowCount(row_num)
                for row in range(row_num):
                    self.tableWidget.setItem(row, 0, QtWidgets.QTableWidgetItem(str(data1[row][0])))
                    self.tableWidget.setItem(row, 1, QtWidgets.QTableWidgetItem(str(data1[row][1])))
            elif (xuanxiang == '班级平均分'):
                sql1 = (" SELECT class.banjibianhao,avg(choose.score) FROM clas"
                    "s,choose,belong where belong.banjibianhao=class.banjibianhao and belong.sno = choose.sno "
                    "GROUP BY class.banjibianhao ORDER BY avg(choose.score) desc")
                cursor.execute(sql1)
                data1 = cursor.fetchall()
                row_num = len(data1)
                self.tableWidget.setRowCount(row_num)
                for row in range(row_num):
                    self.tableWidget.setItem(row, 0, QtWidgets.QTableWidgetItem(str(data1[row][0])))
                    self.tableWidget.setItem(row, 1, QtWidgets.QTableWidgetItem(str(data1[row][1])))
        except:
            QtWidgets.QMessageBox.information(self, '失败', '查询失败', QtWidgets.QMessageBox.Yes |
                                              QtWidgets.QMessageBox.No, QtWidgets.QMessageBox.Yes)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">排名方式</span></p></body></html>"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "班级编号"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "成绩"))
        self.comboBox.setItemText(0, _translate("MainWindow", "班级总分"))
        self.comboBox.setItemText(1, _translate("MainWindow", "班级平均分"))
        self.pushButton.setText(_translate("MainWindow", "确认查询"))
