# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'classxiugai.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import pymysql
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(850, 700)
        MainWindow.setMinimumSize(QtCore.QSize(850, 700))
        MainWindow.setMaximumSize(QtCore.QSize(850, 700))
        MainWindow.setStyleSheet("background-image: url(微信图片_20220430232135.png);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 20, 171, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(70, 120, 61, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(70, 190, 81, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(70, 260, 41, 21))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(70, 330, 41, 21))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(70, 400, 101, 21))
        self.label_6.setObjectName("label_6")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(200, 120, 113, 21))
        self.lineEdit.setStyleSheet("border-radius: 10px;  border: 2px groove gray;\n"
"border-style: outset;")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(200, 190, 113, 21))
        self.lineEdit_2.setStyleSheet("border-radius: 10px;  border: 2px groove gray;\n"
"border-style: outset;")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(200, 260, 113, 21))
        self.lineEdit_3.setStyleSheet("border-radius: 10px;  border: 2px groove gray;\n"
"border-style: outset;")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(200, 330, 113, 21))
        self.lineEdit_4.setStyleSheet("border-radius: 10px;  border: 2px groove gray;\n"
"border-style: outset;")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(200, 400, 113, 21))
        self.lineEdit_5.setStyleSheet("border-radius: 10px;  border: 2px groove gray;\n"
"border-style: outset;")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(450, 410, 121, 61))
        self.pushButton.setStyleSheet("border-radius: 10px;  border: 2px groove gray;\n"
"border-style: outset;")
        self.pushButton.setObjectName("pushButton")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(280, 40, 81, 31))
        self.label_7.setStyleSheet("border-radius: 10px;  border: 2px groove gray;\n"
"border-style: outset;")
        self.label_7.setObjectName("label_7")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_6.setGeometry(QtCore.QRect(390, 40, 111, 31))
        self.lineEdit_6.setStyleSheet("border-radius: 10px;  border: 2px groove gray;\n"
"border-style: outset;")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(550, 40, 81, 31))
        self.pushButton_2.setStyleSheet("border-radius: 10px;  border: 2px groove gray;\n"
"border-style: outset;")
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.pushButton_2.clicked.connect(self.chaxun)
        self.pushButton.clicked.connect(self.xiugai)
    def chaxun(self):
            conn = pymysql.connect(host="localhost", user="root", password="987433", database="keshe01", charset="utf8")
            cursor1 = conn.cursor()  # 得到一个可执行的游标对象
            cno1 = self.lineEdit_6.text()

            if cno1 != '':
                    try:
                        sql1 = "select * from course where course.cno ='%s'" %(cno1)#查询出学生信息,共四条
                        cursor1.execute(sql1)
                        data1 = cursor1.fetchall()
                        self.lineEdit.setText(str(data1[0][0]))
                        self.lineEdit_2.setText(data1[0][1])
                        self.lineEdit_3.setText(str(data1[0][2]))
                        self.lineEdit_4.setText(str(data1[0][3]))
                        self.lineEdit_5.setText(str(data1[0][4]))
                    except:
                            QtWidgets.QMessageBox.information(self, '错误', '导入失败', QtWidgets.QMessageBox.Yes |
                                                              QtWidgets.QMessageBox.No, QtWidgets.QMessageBox.Yes)


    def xiugai(self):
        cno11 = self.lineEdit_6.text()
        cno1=self.lineEdit.text()
        cname1=self.lineEdit_2.text()
        time1=self.lineEdit_3.text()
        fen1=self.lineEdit_4.text()
        xianxiu1=self.lineEdit_5.text()
        conn = pymysql.connect(
            host="localhost",
            user="root",
            password="987433",
            database="keshe01",
            charset="utf8"
        )
        if cno11 != '':
            cursor = conn.cursor()  # 得到一个可执行的游标对象
            try:
                sql1 = ("update course set cno='%s',cname='%s',studytime='%s',xuefen='%s',xianxiucno='%s'"
                        " where course.cno='%s'" % (cno1, cname1, time1, fen1,xianxiu1,cno11))
                cursor.execute(sql1)
                conn.commit()
                cursor.close()
                conn.close()
                QtWidgets.QMessageBox.information(self, '成功', '修改成功', QtWidgets.QMessageBox.Yes |
                                                  QtWidgets.QMessageBox.No, QtWidgets.QMessageBox.Yes)
            except:
                QtWidgets.QMessageBox.information(self, '错误', '修改失败', QtWidgets.QMessageBox.Yes |
                                                  QtWidgets.QMessageBox.No, QtWidgets.QMessageBox.Yes)
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">课程信息修改</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">课程号</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">课程名称</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">学时</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">学分</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">先修课程号</span></p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "确定修改"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">课程号</span></p></body></html>"))
        self.pushButton_2.setText(_translate("MainWindow", "查询"))
