# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lishi.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import pymysql
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(850, 700)
        MainWindow.setMinimumSize(QtCore.QSize(850, 700))
        MainWindow.setMaximumSize(QtCore.QSize(850, 700))
        MainWindow.setStyleSheet("background-image: url(微信图片_20220527085047.png);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(100, 110, 71, 41))
        self.label.setStyleSheet("border-radius: 10px;  border: 2px groove gray;\n"
"border-style: outset;\n"
"border-top:0px solid #e8f3f9;background:  transparent;")
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(192, 115, 151, 31))
        self.lineEdit.setStyleSheet("border-radius: 10px;  border: 2px groove gray;\n"
"border-style: outset; \n"
"border-top:0px solid #e8f3f9;background:  transparent;")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(410, 110, 93, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.pushButton.setPalette(palette)
        self.pushButton.setStyleSheet("border-radius: 10px;  border: 2px groove gray;\n"
"font: 16pt \"Agency FB\";\n"
"border-style: outset;\n"
"border-top:0px solid #e8f3f9;background:  transparent; ")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(530, 110, 93, 41))
        self.pushButton_2.setStyleSheet("border-radius: 10px;  border: 2px groove gray;\n"
"font: 16pt \"Agency FB\";\n"
"border-style: outset;\n"
"border-top:0px solid #e8f3f9;background:  transparent; ")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(650, 110, 93, 41))
        self.pushButton_3.setStyleSheet("border-radius: 10px;  border: 2px groove gray;\n"
"font: 16pt \"Agency FB\";\n"
"border-style: outset;\n"
"border-top:0px solid #e8f3f9;background:  transparent; ")
        self.pushButton_3.setObjectName("pushButton_3")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(30, 280, 791, 241))
        self.tableWidget.setStyleSheet("border-top:0px solid #e8f3f9;background:  transparent; ")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(10)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tableWidget.setHorizontalHeaderItem(9, item)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 20, 151, 41))
        self.label_2.setStyleSheet("border-top:0px solid #e8f3f9;background:  transparent;")
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.pushButton.clicked.connect(self.chaxun)
        self.pushButton_2.clicked.connect(self.huifu)
        self.pushButton_3.clicked.connect(self.infomation)
    def chaxun(self):
        conn = pymysql.connect(
            host="localhost",
            user="root",
            password="987433",
            database="keshe01",
            charset="utf8"
        )
        cursor = conn.cursor()  # 得到一个可执行的游标对象
        sno1 = self.lineEdit.text()
        sql1 = ("select * from `history` where history.sno = '%s'") % (sno1)
        cursor.execute(sql1)
        data=cursor.fetchall()
        try:
            self.tableWidget.clearContents()
            self.tableWidget.setItem(0, 0, QtWidgets.QTableWidgetItem(str(data[0][0])))
            self.tableWidget.setItem(0, 1, QtWidgets.QTableWidgetItem(str(data[0][1])))
            self.tableWidget.setItem(0, 2, QtWidgets.QTableWidgetItem(str(data[0][2])))
            self.tableWidget.setItem(0, 3, QtWidgets.QTableWidgetItem(str(data[0][3])))
            self.tableWidget.setItem(0, 4, QtWidgets.QTableWidgetItem(str(data[0][4])))
            self.tableWidget.setItem(0, 5, QtWidgets.QTableWidgetItem(str(data[0][5])))
            self.tableWidget.setItem(0, 6, QtWidgets.QTableWidgetItem(str(data[0][6])))
            self.tableWidget.setItem(0, 7, QtWidgets.QTableWidgetItem(str(data[0][7])))
            self.tableWidget.setItem(0, 8, QtWidgets.QTableWidgetItem(str(data[0][8])))
            self.tableWidget.setItem(0, 9, QtWidgets.QTableWidgetItem(str(data[0][9])))
        except:
            QtWidgets.QMessageBox.information(self, '错误', '查询失败', QtWidgets.QMessageBox.Yes |
                                              QtWidgets.QMessageBox.No, QtWidgets.QMessageBox.Yes)

        cursor.close()
        conn.close()

    def infomation(self):
        conn = pymysql.connect(
            host="localhost",
            user="root",
            password="987433",
            database="keshe01",
            charset="utf8"
        )
        cursor = conn.cursor()  # 得到一个可执行的游标对象
        sql1 = "select * from history "
        cursor.execute(sql1)
        data = cursor.fetchall()
        row_num = len(data)
        self.tableWidget.setRowCount(row_num)
        try:
            for row in range(row_num):
                self.tableWidget.setItem(row, 0, QtWidgets.QTableWidgetItem(str(data[row][0])))
                self.tableWidget.setItem(row, 1, QtWidgets.QTableWidgetItem(str(data[row][1])))
                self.tableWidget.setItem(row, 2, QtWidgets.QTableWidgetItem(str(data[row][2])))
                self.tableWidget.setItem(row, 3, QtWidgets.QTableWidgetItem(str(data[row][3])))
                self.tableWidget.setItem(row, 4, QtWidgets.QTableWidgetItem(str(data[row][4])))
                self.tableWidget.setItem(row, 5, QtWidgets.QTableWidgetItem(str(data[row][5])))
                self.tableWidget.setItem(row, 6, QtWidgets.QTableWidgetItem(str(data[row][6])))
                self.tableWidget.setItem(row, 7, QtWidgets.QTableWidgetItem(str(data[row][7])))
                self.tableWidget.setItem(row, 8, QtWidgets.QTableWidgetItem(str(data[row][9])))
                self.tableWidget.setItem(row, 9, QtWidgets.QTableWidgetItem(str(data[row][9])))
        except:
            QtWidgets.QMessageBox.information(self, '错误', '查询失败', QtWidgets.QMessageBox.Yes |
                                              QtWidgets.QMessageBox.No, QtWidgets.QMessageBox.Yes)
        cursor.close()
        conn.close()

    def huifu(self):
        conn = pymysql.connect(
            host="localhost",
            user="root",
            password="987433",
            database="keshe01",
            charset="utf8"
        )
        cursor = conn.cursor()  # 得到一个可执行的游标对象

        sno1 = self.lineEdit.text()
        sql1 = "select * from history where history.sno = '%s' " %(sno1)
        cursor.execute(sql1)
        data = cursor.fetchall()
        try:
            sname1 = str(data[0][1])
            sex1 = str(data[0][2])
            address1 = str(data[0][3])
            banji1 = str(data[0][4])
            score1 = str(data[0][5])
            score2 = str(data[0][6])
            score3 = str(data[0][7])
            score4 = str(data[0][8])
            score5 = str(data[0][9])
            sql2 = "insert into belong(belong.sno,belong.banjibianhao) values('%s','%s')" % (sno1, banji1)
            sql8 = "insert into student(sno,sname,sex,address) values('%s','%s','%s','%s')" % (
                sno1, sname1, sex1, address1)
            sql3 = ("insert into choose(sno,cno,score) values('%s','%s','%s')") % (sno1, 100, score1)
            sql4 = ("insert into choose(sno,cno,score) values('%s','%s','%s')") % (sno1, 101, score2)
            sql5 = ("insert into choose(sno,cno,score) values('%s','%s','%s')") % (sno1, 102, score3)
            sql6 = ("insert into choose(sno,cno,score) values('%s','%s','%s')") % (sno1, 103, score4)
            sql7 = ("insert into choose(sno,cno,score) values('%s','%s','%s')") % (sno1, 104, score5)
            sql9 = ("delete from history where history.sno = '%s' ") % (sno1)

            if sno1 != '' and sname1 != '' and sex1 != '' and address1 != '' and banji1 != '' and score1 != ''and score2 != ''and score3 != ''and score4 != ''and score5 != '':
                    cursor = conn.cursor()  # 得到一个可执行的游标对象
                    cursor.execute(sql8)
                    cursor.execute(sql1)
                    cursor.execute(sql2)
                    cursor.execute(sql3)
                    cursor.execute(sql4)
                    cursor.execute(sql5)
                    cursor.execute(sql6)
                    cursor.execute(sql7)
                    cursor.execute(sql9)
                    conn.commit()
                    cursor.close()
                    conn.close()
                    QtWidgets.QMessageBox.information(self, '成功', '恢复信息成功', QtWidgets.QMessageBox.Yes |
                                                  QtWidgets.QMessageBox.No, QtWidgets.QMessageBox.Yes)
        except:
                QtWidgets.QMessageBox.information(self, '错误', '增加失败', QtWidgets.QMessageBox.Yes |
                                                  QtWidgets.QMessageBox.No, QtWidgets.QMessageBox.Yes)
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">学号</span></p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "查询"))
        self.pushButton_2.setText(_translate("MainWindow", "恢复"))
        self.pushButton_3.setText(_translate("MainWindow", "重置"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "学号"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "姓名"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "性别"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "籍贯"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "班级编号"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "数据结构成绩"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "计算机网络成绩"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "大学物理成绩"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "大学英语成绩"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "大学体育成绩"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">历史学生信息</span></p></body></html>"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
