# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'shanchu3.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import pymysql
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(850, 700)
        MainWindow.setMinimumSize(QtCore.QSize(850, 700))
        MainWindow.setMaximumSize(QtCore.QSize(850, 700))
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setStyleSheet("background-image: url(微信图片_20220430232135.png);") #导入图片
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 20, 171, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 100, 61, 31))
        self.label_2.setStyleSheet("border-radius: 10px;  border: 2px groove gray;\n"
"border-style: outset;\n"
"")
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(140, 100, 121, 31))
        self.lineEdit.setStyleSheet("border-radius: 10px;  border: 2px groove gray;\n"
"border-style: outset;\n"
"\n"
"")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(330, 90, 101, 51))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pushButton.setStyleSheet("border-radius: 10px;  border: 2px groove gray;\n"
"border-style: outset;\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(470, 90, 101, 51))
        self.pushButton_2.setStyleSheet("border-radius: 10px;  border: 2px groove gray;\n"
"border-style: outset;\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(60, 200, 681, 381))
        self.tableWidget.setStyleSheet("background-color: rgb(255, 0, 0, 0);")
        self.tableWidget.setColumnCount(9)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tableWidget.setHorizontalHeaderItem(8, item)

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        # 美化表格框
        self.tableWidget.horizontalHeader().setStyleSheet("QHeaderView::section{background-color:rgb(255, 0,0, 0);"
                                                          "font:11pt '宋体';color: black;};")
        self.tableWidget.verticalHeader().setStyleSheet("QHeaderView::section{background-color:rgb(255, 0,0, 0);"
                                                          "font:11pt '宋体';color: black;};")

        self.tableWidget.setShowGrid(False)
        self.pushButton.clicked.connect(self.chaxun)
        self.pushButton_2.clicked.connect(self.delete)
    # 查询学生信息
    def chaxun(self):
        sno1 = self.lineEdit.text()
        conn = pymysql.connect(host="localhost", user="root", password="987433",database="keshe01",charset="utf8")
        sql1 = "select * from `student` where student.sno = '%s'" % (sno1)
        sql2 = "select score from choose,course where choose.sno = '%s' and choose.cno = course.cno" % (sno1)
        cursor1 = conn.cursor()  # 得到一个可执行的游标对象
        cursor1.execute(sql1)
        data1 = cursor1.fetchall()
        cursor2 = conn.cursor()  # 得到
        # 一个可执行的游标对象
        cursor2.execute(sql2)
        data2 = cursor2.fetchall()
        row_num1 = len(data1)
        self.tableWidget.setRowCount(row_num1)
        if sno1 != '':
            try:
                self.tableWidget.setItem(0, 0, QtWidgets.QTableWidgetItem(str(data1[0][0])))
                self.tableWidget.setItem(0, 1, QtWidgets.QTableWidgetItem(data1[0][1]))
                self.tableWidget.setItem(0, 2, QtWidgets.QTableWidgetItem(str(data1[0][2])))
                self.tableWidget.setItem(0, 3, QtWidgets.QTableWidgetItem(str(data1[0][3])))
                self.tableWidget.setItem(0, 4, QtWidgets.QTableWidgetItem(str(data2[0][0])))
                self.tableWidget.setItem(0, 5, QtWidgets.QTableWidgetItem(str(data2[1][0])))
                self.tableWidget.setItem(0, 6, QtWidgets.QTableWidgetItem(str(data2[2][0])))
                self.tableWidget.setItem(0, 7, QtWidgets.QTableWidgetItem(str(data2[3][0])))
                self.tableWidget.setItem(0, 8, QtWidgets.QTableWidgetItem(str(data2[4][0])))


            except:
                QtWidgets.QMessageBox.information(self, '失败', '查询失败', QtWidgets.QMessageBox.Yes |
                                                  QtWidgets.QMessageBox.No, QtWidgets.QMessageBox.Yes)
        cursor1.close()
        cursor2.close()
        conn.close()
    # 删除学生信息
    def delete(self):
        sno1 = self.lineEdit.text()
        conn = pymysql.connect(host="localhost", user="root", password="987433",database="keshe01",charset="utf8")
        sql1 = ("delete from student where student.sno='%s'") % (sno1)
        sql2 = ("delete from choose where choose.sno='%s'") % (sno1)
        sql5=("delete from belong where belong.sno='%s'")%(sno1)
        sql3=("set foreign_key_checks = 0")
        sql4=("set foreign_key_checks = 1")
        sql10=("select * from student where student.sno = '%s'") % (sno1)
        sql6=("select belong.banjibianhao from belong where belong.sno = '%s'") % (sno1)
        sql7 = ("select score from choose,course where choose.sno = '%s' and choose.cno = course.cno") % (sno1)
        cursor1 = conn.cursor()  # 得到一个可执行的游标对象
        cursor2 = conn.cursor()
        cursor3 = conn.cursor()
        cursor4 = conn.cursor()
        cursor1.execute(sql3)
        if sno1 != '':
            try:
                reply = QtWidgets.QMessageBox.question(self, '提示', '确定删除吗', QtWidgets.QMessageBox.Yes |
                                                       QtWidgets.QMessageBox.No)
                cursor2.execute(sql10)
                data1 = cursor2.fetchall()
                cursor3.execute(sql6)
                data2 = cursor3.fetchall()
                cursor4.execute(sql7)
                data3 = cursor4.fetchall()
                sql8 = ("insert into history(sno,sname,sex,address,bianjibianhao,score1,score2,score3,score4,score5) "
                        "values('%s','%s','%s','%s','%s','%s','%s','%s','%s','%s')") % (
                    sno1, data1[0][1], data1[0][2], data1[0][3],data2[0][0],data3[0][0], data3[1][0], data3[2][0],
                    data3[3][0], data3[4][0])

                if (reply == QtWidgets.QMessageBox.Yes):

                    cursor1.execute(sql8)
                    cursor1.execute(sql2)
                    cursor1.execute(sql1)
                    cursor1.execute(sql5)
                    cursor1.execute(sql4)
                    conn.commit()
                    cursor1.close()
                    conn.close()
                    QtWidgets.QMessageBox.information(self, '成功', '删除成功', QtWidgets.QMessageBox.Yes |
                                                      QtWidgets.QMessageBox.No, QtWidgets.QMessageBox.Yes)
                elif (reply == QtWidgets.QMessageBox.No):
                    cursor1.execute(sql4)
                    cursor1.close()
                    conn.close()
            except:
                cursor1.execute(sql4)
                QtWidgets.QMessageBox.information(self, '失败', '删除失败', QtWidgets.QMessageBox.Yes |
                                                  QtWidgets.QMessageBox.No, QtWidgets.QMessageBox.Yes)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">学生信息删除</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">学号</span></p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "查询"))
        self.pushButton_2.setText(_translate("MainWindow", "删除"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "学号"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "姓名"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "性别"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "籍贯"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "数据结构成绩"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "计算机网络成绩"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "大学物理成绩"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "大学英语成绩"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "大学体育成绩"))
