# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'xiugai.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import pymysql
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(850, 700)
        MainWindow.setMinimumSize(QtCore.QSize(850, 700))
        MainWindow.setMaximumSize(QtCore.QSize(850, 700))
        MainWindow.setStyleSheet("background-image: url(微信图片_20220430232135.png);\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 20, 171, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 100, 41, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(60, 160, 41, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(60, 220, 40, 1))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(60, 280, 41, 21))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(60, 340, 121, 21))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(60, 400, 81, 21))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(60, 220, 41, 21))
        self.label_8.setObjectName("label_8")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(140, 100, 111, 21))
        self.lineEdit.setStyleSheet("border-radius: 10px;  border: 2px groove gray;\n"
"border-style: outset;\n"
"")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(140, 160, 113, 21))
        self.lineEdit_2.setStyleSheet("border-radius: 10px;  border: 2px groove gray;\n"
"border-style: outset;\n"
"")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(140, 220, 113, 21))
        self.lineEdit_3.setStyleSheet("border-radius: 10px;  border: 2px groove gray;\n"
"border-style: outset;\n"
"")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(140, 280, 113, 21))
        self.lineEdit_4.setStyleSheet("border-radius: 10px;  border: 2px groove gray;\n"
"border-style: outset;\n"
"")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(210, 340, 113, 21))
        self.lineEdit_5.setStyleSheet("border-radius: 10px;  border: 2px groove gray;\n"
"border-style: outset;\n"
"")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_6.setGeometry(QtCore.QRect(180, 400, 113, 21))
        self.lineEdit_6.setStyleSheet("border-radius: 10px;  border: 2px groove gray;\n"
"border-style: outset;\n"
"")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(390, 460, 141, 61))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pushButton.setStyleSheet("border-radius: 10px;  border: 2px groove gray;\n"
"border-style: outset;\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(390, 100, 121, 21))
        self.label_9.setObjectName("label_9")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_7.setGeometry(QtCore.QRect(550, 100, 113, 21))
        self.lineEdit_7.setStyleSheet("border-radius: 10px;  border: 2px groove gray;\n"
"border-style: outset;\n"
"")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(370, 160, 141, 21))
        self.label_10.setObjectName("label_10")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_8.setGeometry(QtCore.QRect(550, 160, 113, 21))
        self.lineEdit_8.setStyleSheet("border-radius: 10px;  border: 2px groove gray;\n"
"border-style: outset;\n"
"")
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(390, 220, 121, 21))
        self.label_11.setObjectName("label_11")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_9.setGeometry(QtCore.QRect(550, 220, 113, 21))
        self.lineEdit_9.setStyleSheet("border-radius: 10px;  border: 2px groove gray;\n"
"border-style: outset;\n"
"")
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(390, 280, 121, 21))
        self.label_12.setObjectName("label_12")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_10.setGeometry(QtCore.QRect(550, 280, 113, 21))
        self.lineEdit_10.setStyleSheet("border-radius: 10px;  border: 2px groove gray;\n"
"border-style: outset;\n"
"")
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(390, 340, 121, 21))
        self.label_13.setObjectName("label_13")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_11.setGeometry(QtCore.QRect(550, 340, 113, 21))
        self.lineEdit_11.setStyleSheet("border-radius: 10px;  border: 2px groove gray;\n"
"border-style: outset;\n"
"")
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(510, 20, 71, 41))
        self.pushButton_2.setStyleSheet("border-radius: 10px;  border: 2px groove gray;\n"
"border-style: outset;\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(280, 20, 61, 41))
        self.label_14.setStyleSheet("border-radius: 10px;  border: 2px groove gray;\n"
"border-style: outset;\n"
"")
        self.label_14.setObjectName("label_14")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_12.setGeometry(QtCore.QRect(360, 20, 131, 41))
        self.lineEdit_12.setStyleSheet("border-radius: 10px;  border: 2px groove gray;\n"
"border-style: outset;\n"
"")
        self.lineEdit_12.setObjectName("lineEdit_12")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 850, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.pushButton.clicked.connect(self.xiugai)
        self.pushButton_2.clicked.connect(self.chaxun)

    def chaxun(self):
            conn = pymysql.connect(
                    host="localhost",
                    user="root",
                    password="987433",
                    database="keshe01",
                    charset="utf8"
            )
            cursor1 = conn.cursor()  # 得到一个可执行的游标对象
            cursor2 = conn.cursor()
            cursor3 = conn.cursor()
            cursor4 = conn.cursor()
            cursor5 = conn.cursor()
            cursor6 = conn.cursor()
            cursor7 = conn.cursor()
            sno1 = self.lineEdit_12.text()

            if sno1 != '':
                    try:
                        sql1 = "select * from student where student.sno ='%s'" % \
                                  (sno1)#查询出学生信息,共四条
                        sql2 = "select class.banjibianhao,class.zhuanye from class,student,belong where student.sno=belong.sno and " \
                       "belong.banjibianhao=class.banjibianhao and student.sno='%s'"%(sno1)#查询出班级编号和专业，共两条
                        sql3 = "select choose.score from choose where choose.sno='%s' and choose.cno='100'"%(sno1)# 查询学生100的成绩
                        sql4 = "select choose.score from choose where choose.sno='%s' and choose.cno='101'"%(sno1)# 查询学生100的成绩
                        sql5 = "select choose.score from choose where choose.sno='%s' and choose.cno='102'" % (
                        sno1)  # 查询学生100的成绩
                        sql6 = "select choose.score from choose where choose.sno='%s' and choose.cno='103'" % (
                        sno1)  # 查询学生100的成绩
                        sql7 = "select choose.score from choose where choose.sno='%s' and choose.cno='104'" % (
                        sno1)  # 查询学生100的成绩
                        cursor1.execute(sql1)
                        cursor2.execute(sql2)
                        cursor3.execute(sql3)
                        cursor4.execute(sql4)
                        cursor5.execute(sql5)
                        cursor6.execute(sql6)
                        cursor7.execute(sql7)


                        data1 = cursor1.fetchall()
                        data2 = cursor2.fetchall()
                        data3 = cursor3.fetchall()
                        data4 = cursor4.fetchall()
                        data5 = cursor5.fetchall()
                        data6 = cursor6.fetchall()
                        data7 = cursor7.fetchall()


                        #self.tableWidget.setRowCount(row_num)
                        self.lineEdit.setText(str(data1[0][0]))
                        self.lineEdit_2.setText(data1[0][1])
                        self.lineEdit_3.setText(data1[0][2])
                        self.lineEdit_4.setText(data1[0][3])
                        self.lineEdit_5.setText(str(data2[0][0]))
                        self.lineEdit_6.setText(str(data2[0][1]))
                        self.lineEdit_7.setText(str(data3[0][0]))
                        self.lineEdit_8.setText(str(data4[0][0]))
                        self.lineEdit_9.setText(str(data5[0][0]))
                        self.lineEdit_10.setText(str(data6[0][0]))
                        self.lineEdit_11.setText(str(data7[0][0]))
                    except:
                            QtWidgets.QMessageBox.information(self, '错误', '导入失败', QtWidgets.QMessageBox.Yes |
                                                              QtWidgets.QMessageBox.No, QtWidgets.QMessageBox.Yes)

    def xiugai(self):
            sno12=self.lineEdit_12.text()
            sno1 = self.lineEdit.text()
            sname1 = self.lineEdit_2.text()
            sex1 = self.lineEdit_3.text()
            address1 = self.lineEdit_4.text()
            banji1 = self.lineEdit_5.text()
            zhuanye1 = self.lineEdit_6.text()
            score1 = self.lineEdit_7.text()
            score2 = self.lineEdit_8.text()
            score3 = self.lineEdit_9.text()
            score4 = self.lineEdit_10.text()
            score5 = self.lineEdit_11.text()
            conn = pymysql.connect(
                    host="localhost",
                    user="root",
                    password="987433",
                    database="keshe01",
                    charset="utf8"
            )
            sql8=("set foreign_key_checks = 0")
            sql9=("set foreign_key_checks = 1")
            if sno12!='':
                    cursor = conn.cursor()  # 得到一个可执行的游标对象
                    try:

                            sql1 = ("update student set sno='%s',sname='%s',sex='%s',address='%s' where student.sno='%s'" % (
                                    sno1, sname1, sex1, address1,sno12))
                            sql2 = ("update belong,student set belong.sno='%s',"
                                    "belong.banjibianhao='%s' where belong.sno='%s'"% (sno1,banji1,sno12))
                            sql3 = ("update choose set score='%s',sno='%s' where cno='100' and sno='%s'") % (score1,sno1,sno12)
                            sql4 = ("update choose set score='%s',sno='%s' where cno='101' and sno='%s'") % (score2,sno1,sno12)
                            sql5 = ("update choose set score='%s',sno='%s' where cno='102' and sno='%s'") % (score3,sno1,sno12)
                            sql6 = ("update choose set score='%s',sno='%s' where cno='103' and sno='%s'") % (score4,sno1,sno12)
                            sql7 = ("update choose set score='%s',sno='%s' where cno='104' and sno='%s'") % (score5,sno1,sno12)

                            cursor.execute(sql8)
                            cursor.execute(sql3)
                            cursor.execute(sql4)
                            cursor.execute(sql5)
                            cursor.execute(sql6)
                            cursor.execute(sql7)
                            cursor.execute(sql2)
                            cursor.execute(sql1)
                            conn.commit()
                            cursor.execute(sql9)
                            cursor.close()
                            conn.close()
                            QtWidgets.QMessageBox.information(self, '成功', '修改成功', QtWidgets.QMessageBox.Yes |
                                                              QtWidgets.QMessageBox.No, QtWidgets.QMessageBox.Yes)
                    except:
                            QtWidgets.QMessageBox.information(self, '错误', '修改失败', QtWidgets.QMessageBox.Yes |
                                                              QtWidgets.QMessageBox.No, QtWidgets.QMessageBox.Yes)
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">学生信息修改</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">学号</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">姓名</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">性别</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">籍贯</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">所属班级编号</span></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">所属专业</span></p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">性别</span></p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "确定修改"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">数据结构成绩</span></p></body></html>"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">计算机网络成绩</span></p></body></html>"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">大学物理成绩</span></p></body></html>"))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">大学英语成绩</span></p></body></html>"))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">大学体育成绩</span></p></body></html>"))
        self.pushButton_2.setText(_translate("MainWindow", "查询"))
        self.label_14.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; font-style:italic;\">学号</span></p></body></html>"))

