# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'zengjia01.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import pymysql
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(850, 700)
        MainWindow.setMinimumSize(QtCore.QSize(850, 700))
        MainWindow.setMaximumSize(QtCore.QSize(850, 700))
        MainWindow.setStyleSheet("background-image: url(微信图片_20220430232135.png);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 30, 171, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 100, 41, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(60, 160, 41, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(60, 220, 40, 1))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(60, 280, 41, 21))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(60, 340, 121, 21))
        self.label_6.setObjectName("label_6")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(60, 220, 41, 21))
        self.label_8.setObjectName("label_8")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(140, 100, 111, 21))
        self.lineEdit.setStyleSheet("border-radius: 10px;  border: 2px groove gray;\n"
"border-style: outset;")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(140, 160, 113, 21))
        self.lineEdit_2.setStyleSheet("border-radius: 10px;  border: 2px groove gray;\n"
"border-style: outset;")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(140, 220, 113, 21))
        self.lineEdit_3.setStyleSheet("border-radius: 10px;  border: 2px groove gray;\n"
"border-style: outset;")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(140, 280, 113, 21))
        self.lineEdit_4.setStyleSheet("border-radius: 10px;  border: 2px groove gray;\n"
"border-style: outset;")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(210, 340, 113, 21))
        self.lineEdit_5.setStyleSheet("border-radius: 10px;  border: 2px groove gray;\n"
"border-style: outset;")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(320, 420, 131, 51))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pushButton.setStyleSheet("border-radius: 10px;  border: 2px groove gray;\n"
"border-style: outset;")
        self.pushButton.setObjectName("pushButton")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(390, 100, 121, 21))
        self.label_9.setObjectName("label_9")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_7.setGeometry(QtCore.QRect(550, 100, 113, 21))
        self.lineEdit_7.setStyleSheet("border-radius: 10px;  border: 2px groove gray;\n"
"border-style: outset;")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(370, 160, 141, 21))
        self.label_10.setObjectName("label_10")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_8.setGeometry(QtCore.QRect(550, 160, 113, 21))
        self.lineEdit_8.setStyleSheet("border-radius: 10px;  border: 2px groove gray;\n"
"border-style: outset;")
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(390, 220, 121, 21))
        self.label_11.setObjectName("label_11")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_9.setGeometry(QtCore.QRect(550, 220, 113, 21))
        self.lineEdit_9.setStyleSheet("border-radius: 10px;  border: 2px groove gray;\n"
"border-style: outset;")
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(390, 280, 121, 21))
        self.label_12.setObjectName("label_12")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_10.setGeometry(QtCore.QRect(550, 280, 113, 21))
        self.lineEdit_10.setStyleSheet("border-radius: 10px;  border: 2px groove gray;\n"
"border-style: outset;")
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(390, 340, 121, 21))
        self.label_13.setObjectName("label_13")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_11.setGeometry(QtCore.QRect(550, 340, 113, 21))
        self.lineEdit_11.setStyleSheet("border-radius: 10px;  border: 2px groove gray;\n"
"border-style: outset;")
        self.lineEdit_11.setObjectName("lineEdit_11")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 850, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.pushButton.clicked.connect(self.add)
    def add(self):
        sno1 = self.lineEdit.text()
        sname1 = self.lineEdit_2.text()
        sex1 = self.lineEdit_3.text()
        address1 = self.lineEdit_4.text()
        banji1 = self.lineEdit_5.text()
        score1=self.lineEdit_7.text()
        score2=self.lineEdit_8.text()
        score3=self.lineEdit_9.text()
        score4=self.lineEdit_10.text()
        score5=self.lineEdit_11.text()
        conn = pymysql.connect(host="localhost", user="root", password="987433", database="keshe01", charset="utf8")
        sql1 = "insert into student(sno,sname,sex,address) values('%s','%s','%s','%s')" % (
            sno1, sname1, sex1, address1)
        sql2 = "insert into belong(belong.sno,belong.banjibianhao) values('%s','%s')"%(sno1,banji1)
        sql3 = ("insert into choose(sno,cno,score) values('%s','%s','%s')") % (sno1, 100, score1)
        sql4 = ("insert into choose(sno,cno,score) values('%s','%s','%s')") % (sno1, 101, score2)
        sql5 = ("insert into choose(sno,cno,score) values('%s','%s','%s')") % (sno1, 102, score3)
        sql6 = ("insert into choose(sno,cno,score) values('%s','%s','%s')") % (sno1, 103, score4)
        sql7 = ("insert into choose(sno,cno,score) values('%s','%s','%s')") % (sno1, 104, score5)
        try:
            if sno1 != '' and sname1 == '' and sex1 == '' and address1 == '' and banji1 == ''  :
                cursor = conn.cursor()  # 得到一个可执行的游标对象

                cursor.execute(sql3)
                cursor.execute(sql4)
                cursor.execute(sql5)
                cursor.execute(sql6)
                cursor.execute(sql7)
                conn.commit()
                cursor.close()
                conn.close()
                QtWidgets.QMessageBox.information(self, '成功', '增加课程成绩成功', QtWidgets.QMessageBox.Yes |
                                              QtWidgets.QMessageBox.No, QtWidgets.QMessageBox.Yes)

            if sno1 != '' and sname1 != '' and sex1 != '' and address1 != '' and banji1 != '' and score1 != ''and score2 != ''and score3 != ''and score4 != ''and score5 != '':
                    cursor = conn.cursor()  # 得到一个可执行的游标对象
                    cursor.execute(sql1)
                    cursor.execute(sql2)
                    cursor.execute(sql3)
                    cursor.execute(sql4)
                    cursor.execute(sql5)
                    cursor.execute(sql6)
                    cursor.execute(sql7)
                    conn.commit()
                    cursor.close()
                    conn.close()
                    QtWidgets.QMessageBox.information(self, '成功', '增加全部信息成功', QtWidgets.QMessageBox.Yes |
                                                  QtWidgets.QMessageBox.No, QtWidgets.QMessageBox.Yes)
        except:
                QtWidgets.QMessageBox.information(self, '错误', '增加失败', QtWidgets.QMessageBox.Yes |
                                                  QtWidgets.QMessageBox.No, QtWidgets.QMessageBox.Yes)
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">学生信息增加</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">学号</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">姓名</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">性别</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">籍贯</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">所属班级编号</span></p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">性别</span></p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "确定增加"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">数据结构成绩</span></p></body></html>"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">计算机网络成绩</span></p></body></html>"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">大学物理成绩</span></p></body></html>"))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">大学英语成绩</span></p></body></html>"))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">大学体育成绩</span></p></body></html>"))
